[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
categories = ["development-tools"]
description = "GitHub Alfred Workflow to quickly search and open repositories."
edition = "2018"
keywords = [
    "alfred",
    "workflow",
    "github",
]
license = "MIT"
name = "github-workflow"
readme = "README.md"
repository = "https://github.com/rust-playground/alfred-workflows-rs/tree/master/github-workflow"
version = "2.1.0"

[[bin]]
name = "github-workflow"
path = "src/bin/main.rs"

[dependencies]
alfred = "4.0.2"
clap = "2.33.1"
dirs = "3.0.1"
serde_json = "1.0.57"
thiserror = "1.0.20"
anyhow = "1.0.32"

[dependencies.chrono]
features = ["serde"]
version = "0.4.13"

[dependencies.reqwest]
features = ["rustls-tls"]
version = "0.9.22"

[dependencies.rusqlite]
features = [
    "chrono",
    "bundled",
]
version = "0.20.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.114"

[lib]
name = "github_workflow_lib"
path = "src/lib.rs"
