[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
categories = ["development-tools"]
description = "GitHub Alfred Workflow to quickly search and open buildkite pipelines."
edition = "2018"
keywords = [
    "alfred",
    "workflow",
    "buildkite",
]
license = "MIT"
name = "buildkite-workflow"
readme = "README.md"
repository = "https://github.com/rust-playground/alfred-workflows-rs/tree/master/buildkite-workflow"
version = "1.0.0"

[[bin]]
name = "buildkite-workflow"
path = "src/bin/main.rs"

[dependencies]
alfred = "4.0.2"
dirs = "2.0.2"
regex = "1.3.1"
serde_json = "1.0.41"
snafu = "0.6.0"
structopt = "0.3.4"

[dependencies.chrono]
features = ["serde"]
version = "0.4.9"

[dependencies.reqwest]
features = ["rustls-tls"]
version = "0.9.22"

[dependencies.rusqlite]
features = [
    "chrono",
    "bundled",
]
version = "0.20.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.102"

[lib]
name = "buildkite_workflow_lib"
path = "src/lib.rs"
