[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
categories = ["development-tools"]
description = "GitHub Alfred Workflow to quickly search and open buildkite pipelines."
edition = "2018"
keywords = [
    "alfred",
    "workflow",
    "buildkite",
]
license = "MIT"
name = "buildkite-workflow"
readme = "README.md"
repository = "https://github.com/rust-playground/alfred-workflows-rs/tree/master/buildkite-workflow"
version = "1.2.0"

[[bin]]
name = "buildkite-workflow"
path = "src/bin/main.rs"

[dependencies]
alfred = "4.0.2"
dirs = "4.0.0"
regex = "1.8.1"
serde_json = "1.0.96"
anyhow = "1.0.70"
thiserror = "1.0.40"
clap = { version = "3.2.23", features = ["env", "derive"] }

[dependencies.chrono]
features = ["serde"]
version = "0.4.24"

[dependencies.reqwest]
features = ["rustls-tls","blocking", "json"]
version = "0.11.16"

[dependencies.rusqlite]
features = [
    "bundled-full",
]
version = "0.27.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.160"

[lib]
name = "buildkite_workflow_lib"
path = "src/lib.rs"
