[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
categories = ["development-tools"]
description = "GitHub Alfred Workflow to quickly search and open buildkite pipelines."
edition = "2018"
keywords = [
    "alfred",
    "workflow",
    "buildkite",
]
license = "MIT"
name = "buildkite-workflow"
readme = "README.md"
repository = "https://github.com/rust-playground/alfred-workflows-rs/tree/master/buildkite-workflow"
version = "1.1.0"

[[bin]]
name = "buildkite-workflow"
path = "src/bin/main.rs"

[dependencies]
alfred = "4.0.2"
dirs = "4.0.0"
regex = "1.5.4"
serde_json = "1.0.68"
structopt = "0.3.25"
anyhow = "1.0.44"
thiserror = "1.0.30"

[dependencies.chrono]
features = ["serde"]
version = "0.4.19"

[dependencies.reqwest]
features = ["rustls-tls","blocking", "json"]
version = "0.11.6"

[dependencies.rusqlite]
features = [
    "bundled-full",
]
version = "0.26.1"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"

[lib]
name = "buildkite_workflow_lib"
path = "src/lib.rs"
