[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
categories = [
    "date-and-time",
    "development-tools",
]
description = "Date Formats Workflow to quickly handle common data formats and conversions."
edition = "2018"
keywords = [
    "alfred",
    "workflow",
    "date",
    "time",
    "datetime",
]
license = "MIT"
name = "date-formats-workflow"
readme = "README.md"
repository = "https://github.com/rust-playground/alfred-workflows-rs/tree/master/date-formats-workflow"
version = "1.3.0"

[dependencies]
alfred = "4.0.2"
chrono = "0.4.13"
chrono-tz = "0.5.2"
clap = "2.33.1"
thiserror = "1.0.20"
anyhow = "1.0.32"
