[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
categories = [
    "date-and-time",
    "development-tools",
]
description = "Date Formats Workflow to quickly handle common data formats and conversions."
edition = "2018"
keywords = [
    "alfred",
    "workflow",
    "date",
    "time",
    "datetime",
]
license = "MIT"
name = "date-formats-workflow"
readme = "README.md"
repository = "https://github.com/rust-playground/alfred-workflows-rs/tree/master/date-formats-workflow"
version = "1.4.0"

[dependencies]
alfred = "4.0.2"
chrono = "0.4.19"
chrono-tz = "0.6.1"
clap = { version = "3.2.5", features = ["cargo"] }
thiserror = "1.0.31"
anyhow = "1.0.58"
anydate = "0.3.0"
